services:
  app:
    container_name: timecapsule_api
    build:
      context: .
    environment:
      DATABASE_HOST: mariadb
      DATABASE_USERNAME: timecapsule
      DATABASE_PASSWORD: eluspacemit
      DATABASE_NAME: timecapsule
  mariadb:
    container_name: timecapsule_db
    image: mariadb:10.5.23
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_USER: timecapsule
      MARIADB_PASSWORD: eluspacemit
      MARIADB_DATABASE: timecapsule
    volumes:
      - mariadb-volume:/var/lib/mysql

volumes:
  mariadb-volume:
    driver: local
